### ISSUE TITLE
Checkout Bug

### ISSUE THREAD

**Issue by Chadani7** [Dips2020/Colaborative_Development#71]
![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/c4a4818d-7c42-49e2-a3fa-4fd2c18da269)

# While click to the checkout button, It do not working properly

**Comment by 10jing3** [comment]
![image](https://github.com/Dips2020/Colaborative_Development/assets/129353020/283480c9-aa95-4224-b002-fc6692ad2c34)
![image](https://github.com/Dips2020/Colaborative_Development/assets/129353020/d80d5bc3-9c4b-42c8-a90f-3312f39eb3e4)
![image](https://github.com/Dips2020/Colaborative_Development/assets/129353020/6ee072a5-d679-46ef-84f0-0796ccf005bd)
The Bug is fixed and while clicking on checkout all the add to cart will be removed and payment will be successful
