### ISSUE TITLE
Filter By category bug

### ISSUE THREAD

**Issue by Chadani7** [Dips2020/Colaborative_Development#72]
![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/5a18df43-15c5-4c59-a67f-18519a9e1743)

# Encountering a problem in filter y category, It do not responding while trying to click.

**Comment by 10jing3** [comment]
![image](https://github.com/Dips2020/Colaborative_Development/assets/129353020/7f85829c-6bca-47fe-8fd3-b576a748ca7d)
![image](https://github.com/Dips2020/Colaborative_Development/assets/129353020/eab8ac2d-80a7-4bae-af1f-38d0793e0408)

![image](https://github.com/Dips2020/Colaborative_Development/assets/129353020/9de95f1d-71be-4679-ad56-b31e812c1bc9)
The bug is fixed and now the post will be filter accordingly
