### ISSUE TITLE
Read more navigating bug

### ISSUE THREAD

**Issue by Chadani7** [Dips2020/Colaborative_Development#73]
![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/692a9b67-5195-495a-bdf7-56932abbca20)
![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/17a8c70d-7308-4ff2-92b4-6039d2f4c967)

# Encountering a problem in read more button, It do not showing any options for read text.

**Comment by 10jing3** [comment]
![image](https://github.com/Dips2020/Colaborative_Development/assets/129353020/fb5f9a35-4c6b-48bc-81b8-4a469fdef5a6)
![image](https://github.com/Dips2020/Colaborative_Development/assets/129353020/df38dbf3-df4c-473a-b60d-f4b0306f8d99)
![image](https://github.com/Dips2020/Colaborative_Development/assets/129353020/f7a12522-8c93-4fe7-a7dd-a89a200fbe6f)
The bug is fixed and while clicked in Readmore new page while open.
